cpo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('generalzone.urls')),
    url(r'^userzone/',include(('userzone.urls','userzone'),namespace='userzone')),
    url(r'^adminzone/',include(('adminzone.urls','adminzone'),namespace='adminzone'))
]

userzone/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

urlpatterns=[
    path('userhome',views.userhome,name='userhome'),
    url(r'^discussion',views.discussion,name='discussion'),
    url(r'^searchsolution',views.searchsolution,name='searchsolution'),
    url(r'^complainlog',views.complainlog,name='complainlog'),
    url(r'^changepassword',views.changepassword,name='changepassword'),
    url(r'^logout',views.logout,name='logout'),
    url(r'^savecomplain',views.savecomplain,name='savecomplain'),
    url(r'^changepwd',views.changepwd,name='changepwd'),
    url(r'^postquestion',views.postquestion,name='postquestion'),
    url(r'^answer/(?P<qid>\d+)$',views.answer,name='answer'),
    url(r'^postanswer',views.postanswer,name='postanswer'),
    url(r'^viewanswer/(?P<qid>\d+)$',views.viewanswer,name='viewanswer'),
    url(r'^search',views.search,name='search'),
]

userzone/models.py
from django.db import models

# Create your models here.
class Complain(models.Model):
    name=models.CharField(max_length=50)
    gender=models.CharField(max_length=6)
    address=models.TextField()
    contactno=models.CharField(max_length=15)
    emailaddress=models.CharField(max_length=50)
    subject=models.CharField(max_length=200)
    complaintext=models.TextField()
    complaindate=models.CharField(max_length=30)
class Question(models.Model):
    qid=models.AutoField(primary_key=True)
    questiontext=models.TextField()
    askedby=models.CharField(max_length=50)
    posteddate=models.CharField(max_length=30)
class Answer(models.Model):
    aid=models.AutoField(primary_key=True)
    answertext=models.TextField()
    answeredby=models.CharField(max_length=50)
    qid=models.IntegerField()
    answereddate=models.CharField(max_length=30)

userzone/views.py
from django.shortcuts import render,redirect,reverse
from generalzone.models import CustomerInfo,LoginInfo
import datetime
from . models import Complain,Question,Answer
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from adminzone.models import Knowledgebase,Notification
from django.db.models import Q

# Create your views here.
def userhome(request):
    try:   #in case we try to login with userid=null(gets deleted after logout) python gives KeyError
        if request.session['userid']:
            email=request.session.get('userid')
            n=CustomerInfo.objects.get(emailaddress=email)
            name=n.name
            q=Question.objects.all()
            nf=Notification.objects.all()
            return render(request,'userhome.html',{'name':name,'nf':nf,'q':q})
        else:
            return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def discussion(request):
    try:
        if request.session['userid']:
            quest=Question.objects.all()
            return render(request,'discussion.html',{'quest':quest})
        else:
            return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def searchsolution(request):
    try:
        if request.session['userid']:
            name=request.session.get('userid')
            return render(request,'searchsolution.html',{'name':name})
        else:
            return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def complainlog(request):
    try:
        if request.session['userid']:
            name=request.session.get('userid')
            return render(request,'complainlog.html',{'name':name})
        else:
            return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def changepassword(request):
    try:
        if request.session['userid']:
            name=request.session.get('userid')
            return render(request,'changepassword.html',{'name':name})
        else:
            return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def logout(request):
    try:
        del request.session['userid']
        return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def savecomplain(request):
    try:
        if request.session['userid']:
            emailaddress=request.session.get('userid')
            customer=CustomerInfo.objects.get(emailaddress=emailaddress)
            name=customer.name
            gender=customer.gender
            address=customer.address
            contactno=customer.contactno
            subject=request.POST['subject']
            complaintext=request.POST['complaintext']
            complaindate=datetime.datetime.now().strftime('%Y/%m/%d')
            com=Complain(name=name,gender=gender,address=address,contactno=contactno,emailaddress=emailaddress,subject=subject,complaintext=complaintext,complaindate=complaindate)
            com.save()
            messages.success(request,'Complain Lodged Successfully')
            return redirect('userzone:userhome')
        else:
            return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def changepwd(request):
    try:
        if request.session['userid']:
            userid=request.session.get('userid')
            oldpassword=request.POST['oldpassword']
            newpassword=request.POST['newpassword']
            try:
                user=LoginInfo.objects.get(userid=userid,password=oldpassword)
                if user is not None:
                    li=LoginInfo(password=newpassword,userid=userid,usertype='customer')
                    li.save()
                    messages.success(request,'Password Changed Successfully')
                    return redirect('userzone:changepassword')
            except ObjectDoesNotExist:
                messages.warning(request,'Incorrect Password')
                return redirect('userzone:changepassword')
        else:
            return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def postquestion(request):
    try:
        if request.session['userid']:
            emailaddress=request.session.get('userid')
            customer=CustomerInfo.objects.get(emailaddress=emailaddress)
            name=customer.name
            questiontext=request.POST['questiontext']
            posteddate=datetime.datetime.now().strftime('%d/%m/%Y')
            q=Question(questiontext=questiontext,askedby=name,posteddate=posteddate)
            q.save()
            return redirect('userzone:discussion')
        else:
            return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def answer(request,qid):
    try:
        if request.session['userid']:
            return render(request,'answer.html',{'qid':qid})
        else:
            return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def postanswer(request):
    try:
        if request.session['userid']:
            emailaddress=request.session.get('userid')
            customer = CustomerInfo.objects.get(emailaddress=emailaddress)
            answeredby=customer.name
            qid=request.POST['qid']
            answertext=request.POST['answertext']
            answereddate=datetime.datetime.now().strftime('%d/%m/%Y')
            a=Answer(answertext=answertext,answeredby=answeredby,qid=qid,answereddate=answereddate)
            a.save()
            ans=Answer.objects.filter(qid=qid)
            quest=Question.objects.get(qid=qid)
            return render(request,'viewanswer.html',{'ans':ans,'quest':quest})
        else:
            return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def viewanswer(request,qid):
    try:
        if request.session['userid']:
            quest=Question.objects.get(qid=qid)
            ans=Answer.objects.filter(qid=qid)
            return render(request,'viewanswer.html',{'ans':ans,'quest':quest})
        else:
            return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def search(request):
    try:
        if request.session['userid']:
            searchtext=request.POST['searchtext']
            kw=Knowledgebase.objects.filter(Q(problemid=searchtext) | Q(problemtext=searchtext))
            return render(request,'searchsolution.html',{'kw':kw})
    except KeyError:
        return render(request,'login.html')

userzone/templates/answer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link href="{% static 'images\logo.png' %}" rel="icon"/>   <!--fevicon icon-->
    <link href="{% static 'css\style2.css' %}" rel="stylesheet" />
    <title></title>
    <style>
        body
        {
        //background-image: linear-gradient(to top, #48c6ef 0%, #6f86d6 100%);
        background-image:url({% static 'images/bg2.jpg' %});
        background-size:100%;
        background-repeat:no-repeat;
        background-attachment: fixed;
        }

        #menu
        {
        margin-top:30px;
        height:50px;
        width:100%;
        //background-color:black;
        //border:1px solid;
        //border-radius:8px;
        }
        #menu ul
        {
        list-style-type:none;
        }
        #menu ul li
        {
        display:inline;
        padding:15px;
        //color:white;
        //border:1px solid;
        }
        #menu ul li a
        {
        color:#525160;
        font-family:calibri;
        letter-spacing:2px;
        font-size:15px;
        text-decoration:none;
        }
        #menu ul li a:hover
        {
        color:#ec1c24;
        }
        #a1
        {
        height:40px;
        width:140px;
        border:1px solid grey;
        margin-top:55px;
        border-radius:100px;
        background-color:;
        }
        #a2
        {
        height:35px;
        width:35px;
        border-radius:50px;
        border:1px solid;
        margin-top:2px;
        margin-left:2px;
        float:left;
        background-color:lightgrey;
        }
        #a3
        {
        height:35px;
        width:95px;
        //border:1px solid;
        float:left;
        margin-top:2px;
        }
        table
        {
        border-collapse:seperate;
        border-spacing:0 6px;
        }
    </style>
</head>
<body>
<div id="b1">
<div id="outer">
    <div id="p1">
        <div class="s1">
            <a href="{% url 'userzone:userhome' %}"><div class="s3" style="background-image:url('{% static "images/logo.png" %}');background-size:100%;background-repeat:no-repeat;"></div></a>
            <div class="s4">
                <h2><span style="color:white;">C</span>all Processing <span style="color:white;">O</span>ptimisation</h2>
                <h4 style="color:#5b7a9a; margin-left:20px;margin-top:-15px;font-size:15px;letter-spacing:2px;text-shadow:1px 1px 1px;">CUSTOMER SUPPORT</h4>
            </div>
            <div class="s5" style="border:none;">
                {% if name %}
                <h4 style="margin-top:75px;color:#31302c;font-family:calibri;letterspacing:1px;">{{ name }}</h4>
                {% endif %}

            </div>

        </div>
        <hr style="background-color:black;"/>
    <!--Navigation Bar-->
    <div id="menu">
	    <ul>
		    <li><a style="font-weight:900;color:#ec1c24;" href="{% url 'userzone:userhome' %}">HOME</a></li>
		    <li><a href="{% url 'userzone:discussion' %}">DISCUSS</a></li>
		    <!--<li><a href="{% url 'userzone:searchsolution' %}">SEARCH SOLUTION</a></li>-->
		    <li><a href="{% url 'userzone:complainlog' %}">COMPLAIN LOG</a></li>
		    <li><a href="{% url 'userzone:changepassword' %}">CHANGE PASSWORD</a></li>
		    <li><a href="{% url 'userzone:logout' %}">LOGOUT</a></li>
		</ul>
	</div>
    <!--Navigation bar ends-->
    <div class="s6">
        <div class="a4">
        <form action="{% url 'userzone:postanswer' %}" method="post">
            {% csrf_token %}
            <table border="0" style="margin:30px 250px;width:70%;">
                <tr>
                    <td>
                        <textarea class="box4" name="answertext" placeholder="Write your reply..." required ></textarea>
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="hidden" name="qid" value="{{ qid }}"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        <input type="submit" class="button4" value="Post Reply" style="margin-left:538px;"/>
                    </td>
                </tr>
            </table>
        </form>
        </div>
    </div>
    </div>
<div class="s9">
    <div class="s11"></div>
    <div class="s10">
        <h1 style="color:white;">About Us</h1>
        <p style="font-family:calibri;color:#808080;letter-spacing:1px;font-weight:900;font-size:17px;">Hey there! Are you
            stuck with our product.No need to worry, we are here to help you 24x7.  Here at CPO, we all work to ensure that all
        our systems in the hands of our customers work flawlessly.  This website is used to answer important queries about
        our products and provide solution to the user in case he gets stuck somewhere.</p>
    </div>
    <div class="s10">
        <img src="{% static 'images/logo.png' %}" height="100px" width="100px" style="margin-left:140px;margin-top:60px;"/>
        <h3 style="color:white;margin-left:80px;font-family:calibri;">Copyright &copy 2019 CPO.All Rights Reserved</h3>
    </div>
    <div class="s10">
        <h3 style="color:white;margin-left:80px;font-family:calibri;margin-top:130px;">Developed By:- <span style="margin-left:18px;">Aviral Singh</span><br/>
            <span style="margin-left:140px;">CSE Ist year</span><br/><span style="margin-left:140px;">KNIT, Sultanpur</span></h3>
    </div>
</div>
</div>
</div>
</body>
</html>

userzone/templates/changepassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link href="{% static 'images\logo.png' %}" rel="icon"/>   <!--fevicon icon-->
    <link href="{% static 'css\style2.css' %}" rel="stylesheet" />
    <title>Change Password</title>
    <style>
        body
        {
        //background-image: linear-gradient(to top, #48c6ef 0%, #6f86d6 100%);
        background-image:url({% static 'images/bg2.jpg' %});
        background-size:100%;
        background-repeat:no-repeat;
        background-attachment:fixed;
        }
        #menu1
        {
        height:85px;
        width:100%;
        //border:1px solid;

        }
        #menu2
        {
        height:85px;
        width:80px;
        //border:1px solid;
        float:left;
        }
        #menu
        {
        margin-top:15px;
        height:50px;
        width:899px;
        //background-color:black;
        //border:1px solid;
        //border-radius:8px;
        float:left;
        }
        #menu ul
        {
        list-style-type:none;
        }
        #menu ul li
        {
        display:inline;
        padding:15px;
        //color:white;
        //border:1px solid;
        }
        #menu ul li a
        {
        color:#212121;
        font-family:calibri;
        letter-spacing:2px;
        font-size:15px;
        text-decoration:none;
        }
        #menu ul li a:hover
        {
        color:#ec1c24;
        }
        .a1
        {
        height:500px;
        width:40%;
        border:2px solid white;
        background-color:rgba(250,250,250,0.3);
        box-shadow:30px 30px 20px black;
        border-radius:20px;
        position:absolute;
        top:50px;
        left:30%;
        transform-origin:top center;
        transform:rotate(-90deg);
        transform:translateY(-720px);
        animation:drop 1s forwards;
        }
        @keyframes drop
        {
        0%{transform:translateY(-720px);
        opacity:0;}
        70%{transform:translateY(50px);
        opacity:1;}
        100%{transform:translateY(0);}
        }
    </style>
    <script>
            function check()
        {
        var a=document.getElementById('password').value;
        var b=document.getElementById('confirm_password').value;
          if ((a==b)&&(a!='')&&(b!=''))
            {
            document.getElementById('err').style.color = "green";
            document.getElementById('err').innerHTML = "✔";
            return true;
            }
          else if(a!=b)
            {
            document.getElementById('err').style.color = "red";
            document.getElementById('err').innerHTML = "✘";
            return false;
            }
        }
    </script>
</head>
<body>
<div id="outer">
    <div id="p1" style="min-height:600px;">
    <!--Navigation Bar-->
    <div id="menu1">
        <div id="menu2">
            <img src="{% static 'images/logo.png' %}" height="100px" width="100px" style="margin-top:-8px;"/>
        </div>
        <div id="menu">
	    <ul>
		    <li><a href="{% url 'userzone:userhome' %}">HOME</a></li>
		    <li><a href="{% url 'userzone:discussion' %}">DISCUSS</a></li>
		    <!--<li><a href="{% url 'userzone:searchsolution' %}">SEARCH SOLUTION</a></li>-->
		    <li><a href="{% url 'userzone:complainlog' %}">COMPLAIN LOG</a></li>
		    <li><a style="font-weight:900;color:#ec1c24;" href="{% url 'userzone:changepassword' %}">CHANGE PASSWORD</a></li>
		    <li><a href="{% url 'userzone:logout' %}">LOGOUT</a></li>
		</ul>
    </div>
	</div>
        <hr style="background-color:black;"/>
    <!--Navigation bar ends-->
    <div class="s6" id="d1">
        <div class="a1">

        <form action="{% url 'userzone:changepwd' %}" method="post" onsubmit="return check(this);">
            {% csrf_token %}
            <br/>
            <h2 style="color:white;text-align:center;font-family:calibri;font-size:29px;font-weight:400;">CHANGE PASSWORD</h2>
            <table border="0" style="margin:30px 95px;width:70%;" cellspacing="20px">
                <tr>
                    <td align="center">
                        <input type="password" class="box3" name="oldpassword" placeholder="Current Password" required/>
                    </td>
                </tr>

                <tr>
                    <td align="center">
                        <input type="password" class="box3" id="password" name="newpassword" placeholder="New Password" onkeyup="check();" required/>
                    </td>
                    <td>&nbsp &nbsp &nbsp &nbsp &nbsp</td>
                </tr>
                <tr>
                    <td align="center">
                        <input type="password" class="box3" id="confirm_password" name="confirmpassword" placeholder="Confirm New Password" onkeyup="check();" required/>
                    </td>
                    <td>
                        <span id="err" style="font-weight:900;"></span>
                    </td>
                </tr>
            </table>
            <input type="submit" value="RESET" class="button3" onclick="return check();"/>
        </form>
        </div>
    </div>
    </div>
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %} style="list-style-type:none">
            <script>
                var a="{{ message }}";
                alert(a);
            </script>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
<div class="s9">
    <div class="s11"></div>
    <div class="s10">
        <h1 style="color:white;">About Us</h1>
        <p style="font-family:calibri;color:#808080;letter-spacing:1px;font-weight:900;font-size:17px;">Hey there! Are you
            stuck with our product.No need to worry, we are here to help you 24x7.  Here at CPO, we all work to ensure that all
        our systems in the hands of our customers work flawlessly.  This website is used to answer important queries about
        our products and provide solution to the user in case he gets stuck somewhere.</p>
    </div>
    <div class="s10">
        <img src="{% static 'images/logo.png' %}" height="100px" width="100px" style="margin-left:140px;margin-top:60px;"/>
        <h3 style="color:white;margin-left:80px;font-family:calibri;">Copyright &copy 2019 CPO.All Rights Reserved</h3>
    </div>
    <div class="s10">
        <h3 style="color:white;margin-left:80px;font-family:calibri;margin-top:130px;">Developed By:- <span style="margin-left:18px;">Aviral Singh</span><br/>
            <span style="margin-left:140px;">CSE 1st year</span><br/><span style="margin-left:140px;">KNIT, Sultanpur</span></h3>
    </div>
</div>
</div>
</body>
</html>

userzone/templates/discussion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link href='https://fonts.googleapis.com/css?family=Aclonica' rel='stylesheet'>
    <link href="{% static 'images\logo.png' %}" rel="icon"/>   <!--fevicon icon-->
    <link href="{% static 'css\style2.css' %}" rel="stylesheet" />
    <title>Discussion Forum</title>
    <style>
        body
        {
        //background-color:lightgreen;
        background-image:url({% static 'images/bg2.jpg' %});
        //background-image: linear-gradient(to top, #48c6ef 0%, #6f86d6 100%);
        background-size:100%;
        background-repeat:no-repeat;
        background-attachment:fixed;
        }
        #menu
        {
        margin-top:30px;
        height:50px;
        width:1000px;
        //background-color:black;
        //border:1px solid;
        //border-radius:8px;
        }
        #menu ul
        {
        list-style-type:none;
        }
        #menu ul li
        {
        display:inline;
        padding:15px;
        //color:white;
        //border:1px solid;
        }
        #menu ul li a
        {
        color:#212121;
        font-family:calibri;
        letter-spacing:2px;
        font-size:15px;
        text-decoration:none;
        }
        #menu ul li a:hover
        {
        color:#ec1c24;
        }
        #a1
        {
        height:40px;
        width:140px;
        border:1px solid grey;
        margin-top:55px;
        border-radius:100px;
        background-color:;
        }
        #a2
        {
        height:35px;
        width:35px;
        border-radius:50px;
        border:1px solid;
        margin-top:2px;
        margin-left:2px;
        float:left;
        background-color:lightgrey;
        }
        #a3
        {
        height:35px;
        width:95px;
        //border:1px solid;
        float:left;
        margin-top:2px;
        }
        table
        {
        border-collapse:seperate;
        border-spacing:0 6px;
        }
        th
        {
        background-color:#212121;
        color:white;
        padding:12px;
        }
        td:first-child
        {
        border-top-left-radius:10px;
        border-bottom-left-radius:10px;
        }
        td:last-child
        {
        border-top-right-radius:10px;
        border-bottom-right-radius:10px;
        }
        .t1
        {
        background-color:rgba(236,236,236);
        padding:10px;
        }
        #t2
        {
        font-size:18px;
        font-family:calibri;
        font-weight:900;
        text-decoration:none;
        color:black;
        }
        #t2:hover
        {
        text-decoration:underline;
        }
    </style>
</head>
<body>
<div id="outer">
    <div id="p1">
        <div class="s1">
            <a href="{% url 'userzone:userhome' %}"><div class="s3" style="background-image:url('{% static "images/logo.png" %}');background-size:100%;background-repeat:no-repeat;"></div></a>
            <div class="s4">
            <h2 style="margin-top:40px;margin-left:20px;color:#31302c;font-family:aclonica;text-shadow:2px 2px 5px white;" id="txt">Discussion Forum</h2>
            </div>
            <div class="s5" style="border:none;">
                {% if name %}
                <h4 style="margin-top:75px;color:#31302c;font-family:calibri;letterspacing:1px;">{{ name }}</h4>
                {% endif %}

            </div>

        </div>
        <hr style="background-color:black;"/>
    <!--Navigation Bar-->
    <div id="menu">
	    <ul>
		    <li><a href="{% url 'userzone:userhome' %}">HOME</a></li>
		    <li><a style="font-weight:900;color:#ec1c24;" href="{% url 'userzone:discussion' %}">DISCUSS</a></li>
		    <!--<li><a href="{% url 'userzone:searchsolution' %}">SEARCH SOLUTION</a></li>-->
		    <li><a href="{% url 'userzone:complainlog' %}">COMPLAIN LOG</a></li>
		    <li><a href="{% url 'userzone:changepassword' %}">CHANGE PASSWORD</a></li>
		    <li><a href="{% url 'userzone:logout' %}">LOGOUT</a></li>
		</ul>
	</div>
    <!--Navigation bar ends-->
    <div class="s6">
        <div class="a4">
        <form action="{% url 'userzone:postquestion' %}" method="post">
            {% csrf_token %}
        <table border="0" style="margin:20px 250px;width:70%;">
            <tr>
                <td style="font-size:18px;font-weight:900;">&nbsp</td>
            </tr>
            <tr>
                <td>
                    <textarea class="box4" name="questiontext" placeholder="Post a new question..." required></textarea>
                </td>
            </tr>
            <td>
                <input type="submit" value="✚  Create Topic" class="button4" style="margin-left:543px;"/>
            </td>
        </table>
        </form>
        </div>
        <table border="0" style="width:100%;margin:0 auto;">
            <tr>
                <th width="60%">Title</th>
                <th width="20%">Asked By</th>
                <th width="10%">Date Posted</th>
                <th width="10%">&nbsp</th>
                <th>View Answer</th>
            </tr><br/>
            {% for q in quest reversed %}
            <tr>
                <td class="t1" style="max-width:720px;word-wrap:break-word;">►<a id="t2" href="{% url 'userzone:viewanswer' q.qid %}">{{ q.questiontext }}</a></td>
                <td class="t1" align="center">{{ q.askedby }}</td>
                <td class="t1" align="center">{{ q.posteddate }}</td>
                <td class="t1" align="center"><a href="{% url 'userzone:answer' q.qid %}"><button class="button2">Reply</button></a></td>
                <td class="t1" align="center"><a href="{% url 'userzone:viewanswer' q.qid %}"><button class="button2">View</button></a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
    </div>
<div class="s9">
    <div class="s11"></div>
    <div class="s10">
        <h1 style="color:white;">About Us</h1>
        <p style="font-family:calibri;color:#808080;letter-spacing:1px;font-weight:900;font-size:17px;">Hey there! Are you
            stuck with our product.No need to worry, we are here to help you 24x7.  Here at CPO, we all work to ensure that all
        our systems in the hands of our customers work flawlessly.  This website is used to answer important queries about
        our products and provide solution to the user in case he gets stuck somewhere.</p>
    </div>
    <div class="s10">
        <img src="{% static 'images/logo.png' %}" height="100px" width="100px" style="margin-left:140px;margin-top:60px;"/>
        <h3 style="color:white;margin-left:80px;font-family:calibri;">Copyright &copy 2019 CPO.All Rights Reserved</h3>
    </div>
    <div class="s10">
        <h3 style="color:white;margin-left:80px;font-family:calibri;margin-top:130px;">Developed By:- <span style="margin-left:18px;">Aviral Singh</span><br/>
            <span style="margin-left:140px;">CSE Ist year</span><br/><span style="margin-left:140px;">KNIT, Sultanpur</span></h3>
    </div>
</div>
</div>
</body>
</h