adminzone/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^adminhome',views.adminhome,name='adminhome'),
    url(r'^enquiries',views.enquiries,name='enquiries'),
    url(r'^complains',views.complains,name='complains'),
    url(r'^customerinfo',views.customerinfo,name='customerinfo'),
    url(r'^knowledgebase',views.knowledgebase,name='knowledgebase'),
    url(r'^logout',views.logout,name='logout'),
    url(r'^addnotification',views.addnotification,name='addnotification'),
    url(r'^deletenotification/(?P<id>\d+)$',views.deletenotification,name='deletenotification'),
    url(r'^deleteenquiries/(?P<id>\d+)$',views.deleteenquiries,name='deleteenquiries'),
    url(r'^deletecomplain/(?P<id>\d+)$',views.deletecomplain,name='deletecomplain'),
    url(r'^deletecustomerinfo/(?P<emailaddress>[\w.%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4})/$',views.deletecustomerinfo,name='deletecustomerinfo'),
    url(r'^saveknowledgebase',views.saveknowledgebase,name='saveknowledgebase')
]

cpo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('generalzone.urls')),
    url(r'^userzone/',include(('userzone.urls','userzone'),namespace='userzone')),
    url(r'^adminzone/',include(('adminzone.urls','adminzone'),namespace='adminzone'))
]

adminzone/models.py
from django.db import models

# Create your models here.

class Notification(models.Model):
    notificationtext=models.TextField()
    posteddate=models.CharField(max_length=30)
class Knowledgebase(models.Model):
    problemid=models.CharField(max_length=20)
    problemtext=models.TextField()
    solutiontext=models.TextField()
    posteddate=models.CharField(max_length=30)

adminzone/views.py
from django.shortcuts import render,redirect
import datetime
from generalzone.models import Enquiry,CustomerInfo,LoginInfo
from userzone.models import Complain
from django.contrib import messages
from . models import Knowledgebase,Notification


# Create your views here.
def adminhome(request):
    try:   #in case we try to login with adminid=null(gets deleted after logout) python gives KeyError
        if request.session['adminid']:
            name = request.session.get('adminid')
            noti=Notification.objects.all()
            return render(request,'adminhome.html',{'name':name,'noti':noti})
        else:
            return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def enquiries(request):
    try:
        if request.session['adminid']:
            name = request.session.get('adminid')
            enq=Enquiry.objects.all()
            return render(request,'enquiries.html',{'name':name,'enq':enq})
        else:
            return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def complains(request):
    try:
        if request.session['adminid']:
            name = request.session.get('adminid')
            comp=Complain.objects.all()
            return render(request,'complains.html',{'name':name,'comp':comp})
        else:
            return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def customerinfo(request):
    try:
        if request.session['adminid']:
            name = request.session.get('adminid')
            cust=CustomerInfo.objects.all()
            return render(request,'customerinfo.html',{'name':name,'cust':cust})
        else:
            return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def knowledgebase(request):
    try:
        if request.session['adminid']:
            name=request.session.get('adminid')
            return render(request,'knowledgebase.html',{'name':name})
        else:
            return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def logout(request):
    try:
        del request.session['adminid']
        return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def addnotification(request):
    try:
        if request.session['adminid']:
            notificationtext=request.POST['notificationtext']
            posteddate=datetime.datetime.now().strftime('%d/%m/%Y')
            n=Notification(notificationtext=notificationtext,posteddate=posteddate)
            n.save()
            return redirect('adminzone:adminhome')
        else:
            return render(request,'login.html')
    except KeyError:
        return render(request,'login.html')
def deletenotification(request,id):
    try:
        if request.session['adminid']:
            e=Notification.objects.get(id=id)
            e.delete()
            return redirect('adminzone:adminhome')
    except KeyError:
        return render(request,'login.html')
def deleteenquiries(request,id):
    try:
        if request.session['adminid']:
            e=Enquiry.objects.get(id=id)
            e.delete()
            return redirect('adminzone:enquiries')
    except KeyError:
        return render(request,'login.html')
def deletecomplain(request,id):
    try:
        if request.session['adminid']:
            c=Complain.objects.get(id=id)
            c.delete()
            return redirect('adminzone:complains')
    except KeyError:
        return render(request,'login.html')
def deletecustomerinfo(request,emailaddress):
    try:
        if request.session['adminid']:
            c=CustomerInfo.objects.get(emailaddress=emailaddress)
            l=LoginInfo.objects.get(userid=emailaddress)
            c.delete()
            l.delete()
            return redirect('adminzone:customerinfo')
    except KeyError:
        return render(request,'login.html')
def saveknowledgebase(request):
    try:
        if request.session['adminid']:
            problemid=request.POST['problemid']
            problemtext=request.POST['problemtext']
            solutiontext=request.POST['solutiontext']
            posteddate=datetime.datetime.now().strftime('%d/%m/%Y')
            kw=Knowledgebase(problemid=problemid,problemtext=problemtext,solutiontext=solutiontext,posteddate=posteddate)
            kw.save()
            return redirect('adminzone:knowledgebase')
    except KeyError:
        return render(request,'login.html')

adminzone/templates/adminhome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link href="{% static 'images\logo.png' %}" rel="icon"/>   <!--fevicon icon-->
    <link href="{% static 'css\style2.css' %}" rel="stylesheet" />
    <title>Admin: Home</title>
    <style>
        body
        {
        background-color:#74d2e7;
        //background-image:url({% static 'images/bg2.jpg' %});
        background-size:100%;
        background-repeat:no-repeat;
        background-attachment: fixed;
        }

        #menu
        {
        margin-top:30px;
        height:50px;
        width:100%;
        //background-color:black;
        //border:1px solid;
        //border-radius:8px;
        }
        #menu ul
        {
        list-style-type:none;
        }
        #menu ul li
        {
        display:inline;
        padding:15px;
        //color:white;
        //border:1px solid;
        }
        #menu ul li a
        {
        color:#525160;
        font-family:calibri;
        letter-spacing:2px;
        font-size:15px;
        text-decoration:none;
        }
        #menu ul li a:hover
        {
        color:#ec1c24;
        }
        #a1
        {
        height:40px;
        width:140px;
        border:1px solid grey;
        margin-top:55px;
        border-radius:100px;
        background-color:;
        }
        #a2
        {
        height:35px;
        width:35px;
        border-radius:50px;
        border:1px solid;
        margin-top:2px;
        margin-left:2px;
        float:left;
        background-color:lightgrey;
        }
        #a3
        {
        height:35px;
        width:95px;
        //border:1px solid;
        float:left;
        margin-top:2px;
        }

    </style>
</head>
<body>
<div id="b1">
<div id="outer">
    <div id="p1">
        <div class="s1">
            <a href="{% url 'adminzone:adminhome' %}"><div class="s3" style="background-image:url('{% static "images/logo.png" %}');background-size:100%;background-repeat:no-repeat;"></div></a>
            <div class="s4">
                <h2><span style="color:white;">C</span>all Processing <span style="color:white;">O</span>ptimisation</h2>
                <h4 style="color:#5b7a9a; margin-left:20px;margin-top:-15px;font-size:15px;letter-spacing:2px;text-shadow:1px 1px 1px;">CUSTOMER SUPPORT</h4>
            </div>
            <div class="s5" style="border:none;">
                {% if name %}
                <h4 style="margin-top:80px;margin-left:140px;text-transform:uppercase;color:#31302c;font-family:calibri;letterspacing:1px;font-size:20px;">{{ name }}</h4>
                {% endif %}

            </div>

        </div>
        <hr style="background-color:black;"/>
    <!--Navigation Bar-->
    <div id="menu">
	    <ul>
		    <li><a style="font-weight:900;color:#ec1c24;" href="{% url 'adminzone:adminhome' %}">ADMIN HOME</a></li>
		    <li><a href="{% url 'adminzone:enquiries' %}">ENQUIRIES</a></li>
		    <li><a href="{% url 'adminzone:complains' %}">COMPLAINS</a></li>
		    <li><a href="{% url 'adminzone:customerinfo' %}">CUSTOMER INFO</a></li>
		    <li><a href="{% url 'adminzone:knowledgebase' %}">KNOWLEDGE BASE</a></li>
		    <li><a href="{% url 'adminzone:logout' %}">LOGOUT</a></li>
		</ul>
	</div>
    <!--Navigation bar ends-->
    <div class="s6">
        <form method="post" action="{% url 'adminzone:addnotification' %}">
            {% csrf_token %}
            <h2 style="text-align:center;">
                Add Notification
            </h2>
            <table border="0" style="margin:0 460px;width:50%;">
                <tr>
                    <td>&nbsp</td>
                    <td>
                        <textarea name="notificationtext" class="box2" placeholder="Enter Notification..." required style="height:100px;width:250px;resize:none;"></textarea>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp</td>
                    <td>
                        <input style="margin-left:177px;" type="submit" value="Add" class="button2"/>
                    </td>
                </tr>
            </table><br/><br/>
        </form>
        <table border="1" style="width:90%;margin:0 auto;">
            <tr>
                <th>Id</th>
                <th>Notification</th>
                <th>Posted Date</th>
                <th>Delete</th>
            </tr>
            {% for n in noti %}
                <tr>
                    <td align="center">{{ n.id }}</td>
                    <td align="center" style="max-width:300px;word-wrap:break-word;">{{ n.notificationtext }}</td>
                    <td align="center">{{ n.posteddate }}</td>
                    <td align="center">
                        <a href="{% url 'adminzone:deletenotification' n.id %}"><button class="button2">Delete</button></a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    </div>
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %} style="list-style-type:none">
            <script>
                var a="{{ message }}";
                alert(a);
            </script>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
<div class="s9">
    <div class="s11"></div>
    <div class="s10">
        <h1 style="color:white;">About Us</h1>
        <p style="font-family:calibri;color:#808080;letter-spacing:1px;font-weight:900;font-size:17px;">Hey there! Are you
            stuck with our product.No need to worry, we are here to help you 24x7.  Here at CPO, we all work to ensure that all
        our systems in the hands of our customers work flawlessly.  This website is used to answer important queries about
        our products and provide solution to the user in case he gets stuck somewhere.</p>
    </div>
    <div class="s10">
        <img src="{% static 'images/logo.png' %}" height="100px" width="100px" style="margin-left:140px;margin-top:60px;"/>
        <h3 style="color:white;margin-left:80px;font-family:calibri;">Copyright &copy 2019 CPO.All Rights Reserved</h3>
    </div>
    <div class="s10">
        <h3 style="color:white;margin-left:80px;font-family:calibri;margin-top:130px;">Developed By:- <span style="margin-left:18px;">Aviral Singh</span><br/>
            <span style="margin-left:140px;">CSE Ist year</span><br/><span style="margin-left:140px;">KNIT, Sultanpur</span></h3>
    </div>
</div>
</div>
</div>
</body>
</html>

adminzone/templates/complains.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link href="{% static 'images\logo.png' %}" rel="icon"/>   <!--fevicon icon-->
    <link href="{% static 'css\style2.css' %}" rel="stylesheet" />
    <title>Admin: Complains</title>
    <style>
        body
        {
        background-color:#74d2e7;
        //background-image: linear-gradient(to top, #48c6ef 0%, #6f86d6 100%);
        //background-image:url({% static 'images/bg2.jpg' %});
        background-size:100%;
        background-repeat:no-repeat;
        background-attachment: fixed;
        }

        #menu
        {
        margin-top:30px;
        height:50px;
        width:100%;
        //background-color:black;
        //border:1px solid;
        //border-radius:8px;
        }
        #menu ul
        {
        list-style-type:none;
        }
        #menu ul li
        {
        display:inline;
        padding:15px;
        //color:white;
        //border:1px solid;
        }
        #menu ul li a
        {
        color:#525160;
        font-family:calibri;
        letter-spacing:2px;
        font-size:15px;
        text-decoration:none;
        }
        #menu ul li a:hover
        {
        color:#ec1c24;
        }
        #a1
        {
        height:40px;
        width:140px;
        border:1px solid grey;
        margin-top:55px;
        border-radius:100px;
        background-color:;
        }
        #a2
        {
        height:35px;
        width:35px;
        border-radius:50px;
        border:1px solid;
        margin-top:2px;
        margin-left:2px;
        float:left;
        background-color:lightgrey;
        }
        #a3
        {
        height:35px;
        width:95px;
        //border:1px solid;
        float:left;
        margin-top:2px;
        }

    </style>
</head>
<body>
<div id="b1">
<div id="outer">
    <div id="p1">
        <div class="s1">
            <a href="{% url 'adminzone:adminhome' %}"><div class="s3" style="background-image:url('{% static "images/logo.png" %}');background-size:100%;background-repeat:no-repeat;"></div></a>
            <div class="s4">
                <h2><span style="color:white;">C</span>all Processing <span style="color:white;">O</span>ptimisation</h2>
                <h4 style="color:#5b7a9a; margin-left:20px;margin-top:-15px;font-size:15px;letter-spacing:2px;text-shadow:1px 1px 1px;">CUSTOMER SUPPORT</h4>
            </div>
            <div class="s5" style="border:none;">
                {% if name %}
                <h4 style="margin-top:80px;margin-left:140px;text-transform:uppercase;color:#31302c;font-family:calibri;letterspacing:1px;font-size:20px;">{{ name }}</h4>
                {% endif %}

            </div>

        </div>
        <hr style="background-color:black;"/>
    <!--Navigation Bar-->
    <div id="menu">
	    <ul>
		    <li><a href="{% url 'adminzone:adminhome' %}">ADMIN HOME</a></li>
		    <li><a href="{% url 'adminzone:enquiries' %}">ENQUIRIES</a></li>
		    <li><a style="font-weight:900;color:#ec1c24;" href="{% url 'adminzone:complains' %}">COMPLAINS</a></li>
		    <li><a href="{% url 'adminzone:customerinfo' %}">CUSTOMER INFO</a></li>
		    <li><a href="{% url 'adminzone:knowledgebase' %}">KNOWLEDGE BASE</a></li>
		    <li><a href="{% url 'adminzone:logout' %}">LOGOUT</a></li>
		</ul>
	</div>
    <!--Navigation bar ends-->
    <div class="s6">
        <h2 style="text-align:center;">View All Complains</h2><br/>
        <table border="1" style="margin:0 auto;width:100%;">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Gender</th>
                <th>Address</th>
                <th>Contact No.</th>
                <th>Email Address</th>
                <th>Subject</th>
                <th>Complain</th>
                <th>Date</th>
                <th>Delete</th>
            </tr>
            {% for c in comp %}
            <tr>
                <td align="center">{{ c.id }}</td>
                <td align="center">{{ c.name }}</td>
                <td align="center">{{ c.gender }}</td>
                <td align="center">{{ c.address }}</td>
                <td align="center">{{ c.contactno }}</td>
                <td align="center">{{ c.emailaddress }}</td>
                <td align="center">{{ c.subject }}</td>
                <td align="center" style="max-width:200px;word-wrap:break-word;">{{ c.complaintext }}</td>
                <td align="center">{{ c.complaindate }}</td>
                <td align="center">
                    <a href="{% url 'adminzone:deletecomplain' c.id %}"><button class="button2">Delete</button></a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    </div>
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %} style="list-style-type:none">
            <script>
                var a="{{ message }}";
                alert(a);
            </script>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
<div class="s9">
    <div class="s11"></div>
    <div class="s10">
        <h1 style="color:white;">About Us</h1>
        <p style="font-family:calibri;color:#808080;letter-spacing:1px;font-weight:900;font-size:17px;">Hey there! Are you
            stuck with our product.No need to worry, we are here to help you 24x7.  Here at CPO, we all work to ensure that all
        our systems in the hands of our customers work flawlessly.  This website is used to answer important queries about
        our products and provide solution to the user in case he gets stuck somewhere.</p>
    </div>
    <div class="s10">
        <img src="{% static 'images/logo.png' %}" height="100px" width="100px" style="margin-left:140px;margin-top:60px;"/>
        <h3 style="color:white;margin-left:80px;font-family:calibri;">Copyright &copy 2019 CPO.All Rights Reserved</h3>
    </div>
    <div class="s10">
        <h3 style="color:white;margin-left:80px;font-family:calibri;margin-top:130px;">Developed By:- <span style="margin-left:18px;">Aviral Singh</span><br/>
            <span style="margin-left:140px;">CSE Ist year</span><br/><span style="margin-left:140px;">KNIT, Sultanpur</span></h3>
    </div>
</div>
</div>
</div>
</body>
</html>

adminzone/templates/customerinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link href="{% static 'images\logo.png' %}" rel="icon"/>   <!--fevicon icon-->
    <link href="{% static 'css\style2.css' %}" rel="stylesheet" />
    <title>Admin: Customer Info</title>
    <style>
        body
        {
        background-color:#74d2e7;
        //background-image: linear-gradient(to top, #48c6ef 0%, #6f86d6 100%);
        //background-image:url({% static 'images/bg2.jpg' %});
        background-size:100%;
        background-repeat:no-repeat;
        background-attachment: fixed;
        }

        #menu
        {
        margin-top:30px;
        height:50px;
        width:100%;
        //background-color:black;
        //border:1px solid;
        //border-radius:8px;
        }
        #menu ul
        {
        list-style-type:none;
        }
        #menu ul li
        {
        display:inline;
        padding:15px;
        //color:white;
        //border:1px solid;
        }
        #menu ul li a
        {
        color:#525160;
        font-family:calibri;
        letter-spacing:2px;
        font-size:15px;
        text-decoration:none;
        }
        #menu ul li a:hover
        {
        color:#ec1c24;
        }
        #a1
        {
        height:40px;
        width:140px;
        border:1px solid grey;
        margin-top:55px;
        border-radius:100px;
        background-color:;
        }
        #a2
        {
        height:35px;
        width:35px;
        border-radius:50px;
        border:1px solid;
        margin-top:2px;
        margin-left:2px;
        float:left;
        background-color:lightgrey;
        }
        #a3
        {
        height:35px;
        width:95px;
        //border:1px solid;
        float:left;
        margin-top:2px;
        }

    </style>
</head>
<body>
<div id="b1">
<div id="outer">
    <div id="p1">
        <div class="s1">
            <a href="{% url 'adminzone:adminhome' %}"><div class="s3" style="background-image:url('{% static "images/logo.png" %}');background-size:100%;background-repeat:no-repeat;"></div></a>
            <div class="s4">
                <h2><span style="color:white;">C</span>all Processing <span style="color:white;">O</span>ptimisation</h2>
                <h4 style="color:#5b7a9a; margin-left:20px;margin-top:-15px;font-size:15px;letter-spacing:2px;text-shadow:1px 1px 1px;">CUSTOMER SUPPORT</h4>
            </div>
            <div class="s5" style="border:none;">
                {% if name %}
                <h4 style="margin-top:80px;margin-left:140px;text-transform:uppercase;color:#31302c;font-family:calibri;letterspacing:1px;font-size:20px;">{{ name }}</h4>
                {% endif %}

            </div>

        </div>
        <hr style="background-color:black;"/>
    <!--Navigation Bar-->
    <div id="menu">
	    <ul>
		    <li><a href="{% url 'adminzone:adminhome' %}">ADMIN HOME</a></li>
		    <li><a href="{% url 'adminzone:enquiries' %}">ENQUIRIES</a></li>
		    <li><a href="{% url 'adminzone:complains' %}">COMPLAINS</a></li>
		    <li><a style="font-weight:900;color:#ec1c24;" href="{% url 'adminzone:customerinfo' %}">CUSTOMER INFO</a></li>
		    <li><a href="{% url 'adminzone:knowledgebase' %}">KNOWLEDGE BASE</a></li>
		    <li><a href="{% url 'adminzone:logout' %}">LOGOUT</a></li>
		</ul>
	</div>
    <!--Navigation bar ends-->
    <div class="s6">
        <h2 style="text-align:center;">View All Customers</h2><br/>
        <table border="1" style="margin:0 auto;width:100%">
        <tr>
            <th>Name</th>
            <th>Gender</th>
            <th>Address</th>
            <th>Nationality</th>
            <th>Contact No.</th>
            <th>Email Address</th>
            <th>Connect Date</th>
            <th>Delete</th>
        </tr>
            {% for c in cust %}
            <tr>
            <td align="center">{{ c.name }}</td>
            <td align="center">{{ c.gender }}</td>
            <td align="center" style="max-width:300px;word-wrap:break-word;">{{ c.address }}</td>
            <td align="center">{{ c.nationality }}</td>
            <td align="center">{{ c.contactno }}</td>
            <td align="center">{{ c.emailaddress }}</td>
            <td align="center">{{ c.connectdate }}</td>
                <td align="center">
                    <a href="{% url 'adminzone:deletecustomerinfo' emailaddress=c.emailaddress %}"><button class="button2">Delete</button></a>
                </td>
            </tr>
            {% endfor %}
        </table>
    </div>
    </div>
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %} style="list-style-type:none">
            <script>
                var a="{{ message }}";
                alert(a);
            </script>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
<div class="s9">
    <div class="s11"></div>
    <div class="s10">
        <h1 style="color:white;">About Us</h1>
        <p style="font-family:calibri;color:#808080;letter-spacing:1px;font-weight:900;font-size:17px;">Hey there! Are you
            stuck with our product.No need to worry, we are here to help you 24x7.  Here at CPO, we all work to ensure that all
        our systems in the hands of our customers work flawlessly.  This website is used to answer important queries about
        our products and provide solution to the user in case he gets stuck somewhere.</p>
    </div>
    <div class="s10">
        <img src="{% static 'images/logo.png' %}" height="100px" width="100px" style="margin-left:140px;margin-top:60px;"/>
        <h3 style="color:white;margin-left:80px;font-family:calibri;">Copyright &copy 2019 CPO.All Rights Reserved</h3>
    </div>
    <div class="s10">
        <h3 style="color:white;margin-left:80px;font-family:calibri;margin-top:130px;">Developed By:- <span style="margin-left:18px;">Aviral Singh</span><br/>
            <span style="margin-left:140px;">CSE Ist year</span><br/><span style="margin-left:140px;">KNIT, Sultanpur</span></h3>
    </div>
</div>
</div>
</div>
</body>
</html>

adminzone/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>

</body>
</html>